apiVersion: v1
kind: Service
metadata:
  name: apiusersvc
  namespace: ascdev
  labels:
    version: test
spec:
  selector: 
    app: apiuser
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiuserdep
  namespace: ascdev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apiuser
    spec:
      containers:
      - name: api-user
        image: myregistry-on.azurecr.io/asc/api-user:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ascreg